# Generated by Django 3.2.7 on 2021-10-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookcatlog', '0002_list_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_book',
            name='price',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
